apiVersion: v1
kind: Secret
metadata:
  name: db-secret
type: Opaque
data:
  POSTGRES_PASSWORD: cG9zdGdyZXM= # Base64 encoded 'postgres'
  DATABASE_URL: cG9zdGdyZXM6cG9zdGdyZXNAcG9zdGdyZXMtc2VydmljZTpw9zdGdyZXM= # Base64 encoded 'postgres:postgres@postgres-service:postgres'
